    # APK Download page
    location ^~ /download {
        alias /var/www/robifel-download;
        index index.html;
        try_files $uri $uri/ =404;
        types { application/vnd.android.package-archive apk; text/html html; }
    }
